name: development
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - numpy==1.23.5
    - rule-engine==3.5.1
    - azure-eventgrid
    - ray==2.3.0
    - sentencepiece==0.1.97
    - transformers==4.25.1
    - sentence-transformers==2.2.2
    - umap==0.1.1
    - hdbscan
    - bertopic==0.13.0
    - opencensus-ext-azure
    - opencensus-ext-logging
    - azure-storage-blob
    - flashtext==2.7
    - protobuf==3.20.1
    - spark-nlp==4.0.2
    - pyvis==0.3.2
